name:                haskell-service-template
version:             0.1.0.0
github:              "githubuser/haskell-service-template"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-service-template#readme>

dependencies:
- base >= 4.7 && < 5
- rio
- unliftio
- conduit
- conduit-extra
- aeson
- aeson-pretty
- attoparsec
- attoparsec-binary
- text
- servant
- servant-server
- warp
- hspec
- wai
- servant-client
- http-client
- http-types
- persistent
- persistent-sqlite
- esqueleto
- monad-logger
- hw-kafka-client
- containers
- envy
- vault
- random
- fast-logger
- resource-pool
- haskell-service-lib

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  - LambdaCase
  - OverloadedRecordDot
  - OverloadedStrings
  - NoImplicitPrelude
  - BangPatterns
  - BinaryLiterals
  - DeriveGeneric
  - ScopedTypeVariables
  - DataKinds
  - TypeOperators
  - RecordWildCards
  - FunctionalDependencies
  - AllowAmbiguousTypes
  - TypeApplications
  - FlexibleInstances
  - UndecidableInstances
  - DerivingStrategies
  - DeriveAnyClass


library:
  source-dirs: src

executables:
  haskell-service-template-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-service-template

  run-migrations:
    main:                Main.hs
    source-dirs:         migrations-app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-service-template

tests:
  haskell-service-template-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-service-template
