name:                haskell-service-lib
version:             0.1.0.0
github:              "githubuser/haskell-service-lib"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Shared infrastructure for Haskell microservices

dependencies:
- base >= 4.7 && < 5
- rio
- aeson
- hw-kafka-client
- persistent
- persistent-sqlite
- persistent-postgresql
- containers
- text
- wai
- vault
- random
- monad-logger
- resource-pool
- fast-logger
- envy
- time
- http-client
- http-client-tls
- http-types
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  - LambdaCase
  - OverloadedRecordDot
  - OverloadedStrings
  - NoImplicitPrelude
  - BangPatterns
  - DeriveGeneric
  - ScopedTypeVariables
  - DataKinds
  - TypeOperators
  - FlexibleInstances
  - RecordWildCards
  - TypeApplications

library:
  source-dirs: src
  exposed-modules:
    - Service.Kafka
    - Service.Test.Kafka
    - Service.CorrelationId
    - Service.Database
    - Service.Server
    - Service.HttpClient
    - Service.Test.HttpClient

tests:
  haskell-service-lib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-service-lib
    - hspec
